# Generated by Django 4.2.5 on 2023-10-25 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appUser', '0003_userinfo'),
        ('appMy', '0003_alter_popular_image_netflix'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Başlık')),
                ('text', models.TextField(default='', verbose_name='Açıklama')),
                ('image', models.FileField(upload_to='mylist', verbose_name='Film Afişi')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appMy.category', verbose_name='Kategori')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appUser.profile')),
            ],
        ),
    ]
